### ISSUE TITLE
Data Classes?

### ISSUE THREAD

**Issue by rbbl-dev** [pcimcioch/gitlab-ci-kotlin-dsl#3]
Hello,

is there any specific reason why you used regular classes over data classes for all Dsl Objects?

**Comment by pcimcioch** [comment]
Hi!

Good question. I went through the DSL classes to see if they could be a data classes.

I think the biggest potential issue would be encapsulation. Note that some of DSL classes contain private fields. And it is by design. I don't want to expose them, as they are not independent. You can't set them independently of other fields. For example [CacheDsl](https://github.com/pcimcioch/gitlab-ci-kotlin-dsl/blob/master/src/main/kotlin/pcimcioch/gitlabci/dsl/job/CacheDsl.kt) or [InheritDsl](https://github.com/pcimcioch/gitlab-ci-kotlin-dsl/blob/master/src/main/kotlin/pcimcioch/gitlabci/dsl/job/InheritDsl.kt)

Another thing is inheritance. Generally, data classes in kotlin do not play well with inheritance. They can be "last" leaf of inheritance, but not "in the middle" - they can't be `open`. All DSL classes in this project participate in some inheritance tree. However, maybe this wouldn't be such a big issue.

I always considered data classes good candidates for "simpler structures". Things like a `Point` or `Pair`. Classes that you use specyfically to unite simple sub-components. And DSL classes that I created in this project are just more complex.

I could also try making some of the classes "data classes", and the ones with more complex structure - like the one needing better encapsulation - "standard classes". But I just prefer consistency. All or none.

However, I'm not saying that data class is always a bad choice for the DSL. Far from that; I'm sure you could achive many DSL designs in which data classes fits right in. 
Disclaimer: I created this project to learn Kotlin, its DSL and Serializtion API and I'm not kotlin developer by trade - I fully admit that this DSL design may not follow the best kotlin practices :)

**Comment by rbbl-dev** [comment]
i see, thanks for elaborating.
forgot that about those limitations on data classes.

i guess i'm gonna open a PR sometime soon to add equals and hashcode functions.

turned out quite well for a learning project imo :)
